/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AgendaController;

/**
 *
 * @author Frederico
 */
public class Agenda extends javax.swing.JFrame {
    private final AgendaController controller;
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Cliente = new javax.swing.JLabel();
        jComboBox_Cliente = new javax.swing.JComboBox<>();
        Lbl_Servico = new javax.swing.JLabel();
        jComboBox_Servico = new javax.swing.JComboBox<>();
        Lbl_Valor = new javax.swing.JLabel();
        Txt_Valor = new javax.swing.JTextField();
        Lbl_Data = new javax.swing.JLabel();
        Txt_Data = new javax.swing.JTextField();
        Lbl_Hora = new javax.swing.JLabel();
        Txt_Hora = new javax.swing.JTextField();
        Lbl_Observacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_Observacao = new javax.swing.JTextArea();
        Button_Agendar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_Agendamentos = new javax.swing.JTable();
        Button_CancelarAgendamento = new javax.swing.JButton();
        Button_Cancelar = new javax.swing.JButton();
        Lbl_AgendaPainelFundo1 = new javax.swing.JLabel();
        Lbl_Agenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_Cliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Lbl_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Cliente.setText("Cliente:");
        getContentPane().add(Lbl_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jComboBox_Cliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jComboBox_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 280, -1));

        Lbl_Servico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Lbl_Servico.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Servico.setText("Serviço:");
        getContentPane().add(Lbl_Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jComboBox_Servico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_Servico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox_Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 280, -1));

        Lbl_Valor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Lbl_Valor.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Valor.setText("Valor R$:");
        getContentPane().add(Lbl_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        Txt_Valor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Txt_Valor.setText("0");
        Txt_Valor.setToolTipText("");
        getContentPane().add(Txt_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 280, -1));

        Lbl_Data.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Lbl_Data.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Data.setText("Data:");
        getContentPane().add(Lbl_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        Txt_Data.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Txt_Data.setToolTipText("");
        getContentPane().add(Txt_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 280, -1));

        Lbl_Hora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Lbl_Hora.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Hora.setText("Hora:");
        getContentPane().add(Lbl_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        Txt_Hora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Txt_Hora.setToolTipText("");
        getContentPane().add(Txt_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 280, -1));

        Lbl_Observacao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Lbl_Observacao.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Observacao.setText("Observação:");
        getContentPane().add(Lbl_Observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        jTextArea1_Observacao.setColumns(20);
        jTextArea1_Observacao.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_Observacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 420, 310));

        Button_Agendar.setBackground(new java.awt.Color(102, 255, 102));
        Button_Agendar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_Agendar.setForeground(new java.awt.Color(255, 255, 255));
        Button_Agendar.setText("Agendar");
        Button_Agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AgendarActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 420, -1));

        jTable1_Agendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jScrollPane2.setViewportView(jTable1_Agendamentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 1170, 240));

        Button_CancelarAgendamento.setBackground(new java.awt.Color(102, 255, 102));
        Button_CancelarAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_CancelarAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        Button_CancelarAgendamento.setText("Cancelar agendamento");
        Button_CancelarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(Button_CancelarAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 940, 420, -1));

        Button_Cancelar.setBackground(new java.awt.Color(102, 255, 102));
        Button_Cancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Button_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Button_Cancelar.setText("Cancelar");
        Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 940, 420, -1));

        Lbl_AgendaPainelFundo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frederico\\Documents\\projetos privados\\BarbeariaComentariosNetBeansYouTube\\refazendoBarbeariaAula\\src\\main\\java\\com\\mycompany\\refazendobarbeariaaula\\view\\img\\Agenda-PainelFundo.png")); // NOI18N
        getContentPane().add(Lbl_AgendaPainelFundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, 1030));

        Lbl_Agenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Frederico\\Documents\\projetos privados\\BarbeariaComentariosNetBeansYouTube\\refazendoBarbeariaAula\\src\\main\\java\\com\\mycompany\\refazendobarbeariaaula\\view\\img\\AgendaFundo.png")); // NOI18N
        getContentPane().add(Lbl_Agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarActionPerformed
        controller.cancelar();
    }//GEN-LAST:event_Button_CancelarActionPerformed

    private void jComboBox_ServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ServicoItemStateChanged
        controller.atualizarValor();
    }//GEN-LAST:event_jComboBox_ServicoItemStateChanged

    private void Button_AgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AgendarActionPerformed
        controller.inserirDadosBanco();
    }//GEN-LAST:event_Button_AgendarActionPerformed

    private void Button_CancelarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarAgendamentoActionPerformed
        controller.cancelarAgendamentoView();
    }//GEN-LAST:event_Button_CancelarAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Agendar;
    private javax.swing.JButton Button_Cancelar;
    private javax.swing.JButton Button_CancelarAgendamento;
    private javax.swing.JLabel Lbl_Agenda;
    private javax.swing.JLabel Lbl_AgendaPainelFundo1;
    private javax.swing.JLabel Lbl_Cliente;
    private javax.swing.JLabel Lbl_Data;
    private javax.swing.JLabel Lbl_Hora;
    private javax.swing.JLabel Lbl_Observacao;
    private javax.swing.JLabel Lbl_Servico;
    private javax.swing.JLabel Lbl_Valor;
    private javax.swing.JTextField Txt_Data;
    private javax.swing.JTextField Txt_Hora;
    private javax.swing.JTextField Txt_Valor;
    private javax.swing.JComboBox<String> jComboBox_Cliente;
    private javax.swing.JComboBox<String> jComboBox_Servico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1_Agendamentos;
    private javax.swing.JTextArea jTextArea1_Observacao;
    // End of variables declaration//GEN-END:variables
    
    public void iniciar() {
        controller.atualizarTabela();
        controller.atualizarCliente();
        controller.atualizarServico();
        controller.atualizarValor();
    }
    
    public javax.swing.JTable getjTable1_Agendamentos() {
        return jTable1_Agendamentos;
    }

    public void setjTable1_Agendamentos(javax.swing.JTable jTable1_Agendamentos) {
        this.jTable1_Agendamentos = jTable1_Agendamentos;
    }

    public javax.swing.JComboBox<String> getjComboBox_Cliente() {
        return jComboBox_Cliente;
    }

    public void setjComboBox_Cliente(javax.swing.JComboBox<String> jComboBox_Cliente) {
        this.jComboBox_Cliente = jComboBox_Cliente;
    }

    public javax.swing.JComboBox<String> getjComboBox_Servico() {
        return jComboBox_Servico;
    }

    public void setjComboBox_Servico(javax.swing.JComboBox<String> jComboBox_Servico) {
        this.jComboBox_Servico = jComboBox_Servico;
    }

    public javax.swing.JTextField getTxt_Valor() {
        return Txt_Valor;
    }

    public void setTxt_Valor(javax.swing.JTextField Txt_Valor) {
        this.Txt_Valor = Txt_Valor;
    }

    public javax.swing.JTextField getTxt_Data() {
        return Txt_Data;
    }

    public void setTxt_Data(javax.swing.JTextField Txt_Data) {
        this.Txt_Data = Txt_Data;
    }

    public javax.swing.JTextField getTxt_Hora() {
        return Txt_Hora;
    }

    public void setTxt_Hora(javax.swing.JTextField Txt_Hora) {
        this.Txt_Hora = Txt_Hora;
    }

    public javax.swing.JTextArea getjTextArea1_Observacao() {
        return jTextArea1_Observacao;
    }

    public void setjTextArea1_Observacao(javax.swing.JTextArea jTextArea1_Observacao) {
        this.jTextArea1_Observacao = jTextArea1_Observacao;
    }
/*
    public javax.swing.JTextField getTxt_Id() {
        return Txt_Id;
    }

    public void setTxt_Id(javax.swing.JTextField Txt_Id) {
        this.Txt_Id = Txt_Id;
    }
  */  

    public javax.swing.JButton getButton_Cancelar() {
        return Button_Cancelar;
    }

    public void setButton_Cancelar(javax.swing.JButton Button_Cancelar) {
        this.Button_Cancelar = Button_Cancelar;
    }
    

}
